version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./deploy/default.conf:/etc/nginx/sites-enabled/default