version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile
      target: development
    image: gnussonnet/dockerized-nginx-letsencrypt-react:development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src