version: "3.7"
services:
  frontend:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./frontend:/var/www/html
      - ./deploy/default.conf:/etc/nginx/sites-available/default